import Section from '../components/Section.jsx'
import CodeBlock from '../components/CodeBlock.jsx'

export default function VariadicGenerics() {
  return (
    <Section id="variadic-generics" title="Variadic Generics">
      <p className="mt-2 text-az-35">
        Variadic generics extend the generic system to support a variable number of type
        parameters. The core syntax is <code className="text-az-primary">T...</code>, which
        declares a type parameter pack. Each element in the pack can have a different type, and
        the compiler tracks all of them individually. Fully monomorphized at compile time with
        no runtime overhead.
      </p>

      <h3 className="text-lg font-semibold mt-6 mb-2 text-az-25">20.1 Variadic Type Parameters (T...)</h3>
      <p className="mt-2 text-az-35">
        Declare a variadic type parameter by appending <code className="text-az-primary">...</code>{' '}
        to the type parameter name. This creates a type parameter pack that accepts any number
        of type arguments. Use it in pack definitions to create types with a variable number of
        fields.
      </p>
      <CodeBlock>{`pack Tuple<T...> {
    inline for Ty in T with $index {
        t$index: Ty = _
    }
}

var t: Tuple<Int, String, Bool> = Tuple<Int, String, Bool>(
    t0: 1, t1: "hi", t2: true
)`}</CodeBlock>
      <p className="mt-2 text-az-35">
        The preprocessor expands this into a concrete pack with numbered fields:
      </p>
      <CodeBlock>{`// Generated by the preprocessor:
pack Tuple__Int__String__Bool {
    t0: Int = 0
    t1: String = ""
    t2: Bool = false
}`}</CodeBlock>

      <h3 className="text-lg font-semibold mt-6 mb-2 text-az-25">20.2 Each Keyword</h3>
      <p className="mt-2 text-az-35">
        The <code className="text-az-primary">where each</code> clause applies a spec constraint
        to every individual type in the pack. If any type in the pack fails the constraint, the
        preprocessor reports a compile-time error.
      </p>
      <CodeBlock>{`func<T...> add(args: T...): Int
where each T: Numeric {
    var sum = 0
    for arg in args {
        sum += arg
    }
    return sum
}

var x = add(2, 3, 7, 9)         // OK: all Int, all Numeric
var bad = add(2, "hello", 7)    // ERROR: String does not implement Numeric`}</CodeBlock>
      <p className="mt-2 text-az-35">
        The <code className="text-az-primary">each</code> keyword ensures the constraint is
        checked per-element, not on the pack as a whole.
      </p>

      <h3 className="text-lg font-semibold mt-6 mb-2 text-az-25">20.3 Inline For with Type Lists</h3>
      <p className="mt-2 text-az-35">
        Use <code className="text-az-primary">inline for</code> to iterate over a type parameter
        pack at compile time. The loop body is expanded once per type in the pack. The{' '}
        <code className="text-az-primary">with $index</code> clause provides a compile-time
        index for generating unique names.
      </p>
      <CodeBlock>{`pack Record<T...> {
    inline for Ty in T with $index {
        field$index: Ty = _
    }
}

// Tuple<Int, Real, String> generates:
// field0: Int = 0
// field1: Real = 0.0
// field2: String = ""`}</CodeBlock>
      <p className="mt-2 text-az-35">
        <code className="text-az-primary">inline for</code> is a compile-time construct, not a
        runtime loop. It only works with type parameter packs known at compile time.
      </p>

      <h3 className="text-lg font-semibold mt-6 mb-2 text-az-25">20.4 Tuple Packs</h3>
      <p className="mt-2 text-az-35">
        The most common use of variadic generics is building tuple types. A tuple pack holds a
        heterogeneous collection of values, each with its own type. The syntax{' '}
        <code className="text-az-primary">args: T...</code> in a function parameter list accepts
        one argument for each type in the pack.
      </p>
      <CodeBlock>{`func<T...> makeTuple(args: T...): Tuple<T...> {
    return Tuple<T...>(args)
}

var t = makeTuple(42, "hello", true)
// t.t0 == 42
// t.t1 == "hello"
// t.t2 == true`}</CodeBlock>
      <p className="mt-2 text-az-35">
        The <code className="text-az-primary">promote!</code> type function computes the widest
        type across all pack members, useful for reduction functions:
      </p>
      <CodeBlock>{`func<T...> add(args: T...): promote!T
where each T: Numeric {
    var sum: ReturnType = _
    for arg in args {
        sum += arg
    }
    return sum
}

var x = add(2, 3.4, 7, 9, 1.2)    // promote!T is Real`}</CodeBlock>

      <h3 className="text-lg font-semibold mt-6 mb-2 text-az-25">20.5 Length Constraints</h3>
      <p className="mt-2 text-az-35">
        Constrain the pack's length with a <code className="text-az-primary">where</code> clause
        using <code className="text-az-primary">T.length</code>. This prevents instantiation
        with too few or too many type arguments.
      </p>
      <CodeBlock>{`pack Tuple<T...> where T.length >= 2 {
    inline for Ty in T with $index {
        t$index: Ty = _
    }
}

// OK: 3 type arguments
var t = Tuple<Int, String, Bool>(t0: 1, t1: "hi", t2: true)

// ERROR: fewer than 2 type arguments
var bad = Tuple<Int>(t0: 1)`}</CodeBlock>
      <p className="mt-2 text-az-35">
        Length constraints support the comparison operators{' '}
        <code className="text-az-primary">==</code>, <code className="text-az-primary">!=</code>,{' '}
        <code className="text-az-primary">&lt;</code>, <code className="text-az-primary">&gt;</code>,{' '}
        <code className="text-az-primary">&lt;=</code>, and <code className="text-az-primary">&gt;=</code>.
      </p>

      <p className="mt-4 text-sm text-az-50">
        Variadic generics are fully resolved at compile time. The preprocessor expands{' '}
        <code className="text-az-primary">T...</code> into concrete types,{' '}
        <code className="text-az-primary">inline for</code> into repeated declarations, and{' '}
        <code className="text-az-primary">promote!</code> into a single concrete type. The
        generated code contains no traces of the variadic machinery.
      </p>
    </Section>
  )
}
